version: '3'
networks:
  tp-docker:
    ipam:
      config:
        - subnet: 172.22.0.0/24
services:
  api-backend:
    image: api-backend:latest
    build:
      context: ./api-backend/
      dockerfile: Dockerfile
    container_name: api-backend
    restart: unless-stopped
    networks:
      tp-docker:
        ipv4_address: 172.22.0.10
    ports:
      - 8001:8001
  api-frontend:
    image: api-frontend:latest
    build:
      context: ./api-frontend/
      dockerfile: Dockerfile
    container_name: api-frontend
    restart: unless-stopped
    networks:
      tp-docker:
        ipv4_address: 172.22.0.20
    ports:
      - 8000:8000
    environment:
      - API_BACKEND_URL=172.22.0.10
      - API_BACKEND_PORT=8001
    depends_on:
      - api-backend
